package idlmodule;


/**
* idlmodule/corba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, 5 August, 2021 8:11:48 PM EDT
*/

public interface corba extends corbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface corba
