package corba;

/**
* DcmsApp/DcmsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 25 July, 2018 11:10:23 PM EDT
*/

public final class DcmsHolder implements org.omg.CORBA.portable.Streamable
{
  public Dcms value = null;

  public DcmsHolder ()
  {
  }

  public DcmsHolder (Dcms initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DcmsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DcmsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DcmsHelper.type ();
  }

}
