package corba;


/**
* DcmsApp/DcmsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 25 July, 2018 11:10:23 PM EDT
*/

abstract public class DcmsHelper
{
  private static String  _id = "IDL:DcmsApp/Dcms:1.0";

  public static void insert (org.omg.CORBA.Any a, Dcms that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Dcms extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DcmsHelper.id (), "Dcms");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Dcms read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DcmsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Dcms value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Dcms narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Dcms)
      return (Dcms)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _DcmsStub stub = new _DcmsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Dcms unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Dcms)
      return (Dcms)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _DcmsStub stub = new _DcmsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
