package ca.concordia.dsd.arch;


/**
* arch/corbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Friday, 2 July, 2021 10:52:21 PM EDT
*/

public interface corbaOperations 
{
  String createTRecord (String id, String fName, String lName, String address, String phone, String specialization, String location);
  String createSRecord (String id, String fName, String lName, String courses, boolean status, String statusDate);
  String getRecordCounts (String id);
  String editRecord (String id, String recordID, String fieldName, String newValue);
  String transferRecord (String id, String recordId, String remoteCenterServerName);
} // interface corbaOperations
