package ca.concordia.dsd.arch;


/**
* ca.concordia.dsd.arch/corba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Wednesday, 4 August, 2021 11:37:50 PM EDT
*/

public interface corba extends corbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface corba
