package ca.concordia.dsd.arch;


/**
* ca.concordia.dsd.arch/corbaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, 5 August, 2021 2:30:22 PM EDT
*/

public abstract class corbaPOA extends org.omg.PortableServer.Servant
 implements ca.concordia.dsd.arch.corbaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createTRecord", new java.lang.Integer (0));
    _methods.put ("createSRecord", new java.lang.Integer (1));
    _methods.put ("getRecordCounts", new java.lang.Integer (2));
    _methods.put ("editRecord", new java.lang.Integer (3));
    _methods.put ("transferRecord", new java.lang.Integer (4));
    _methods.put ("killPrimaryServer", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ca.concordia.dsd.arch/corba/createTRecord
       {
         String id = in.read_string ();
         String fName = in.read_string ();
         String lName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String specialization = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.createTRecord (id, fName, lName, address, phone, specialization, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ca.concordia.dsd.arch/corba/createSRecord
       {
         String id = in.read_string ();
         String fName = in.read_string ();
         String lName = in.read_string ();
         String courses = in.read_string ();
         boolean status = in.read_boolean ();
         String statusDate = in.read_string ();
         String $result = null;
         $result = this.createSRecord (id, fName, lName, courses, status, statusDate);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ca.concordia.dsd.arch/corba/getRecordCounts
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ca.concordia.dsd.arch/corba/editRecord
       {
         String id = in.read_string ();
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String $result = null;
         $result = this.editRecord (id, recordID, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ca.concordia.dsd.arch/corba/transferRecord
       {
         String id = in.read_string ();
         String recordId = in.read_string ();
         String remoteCenterServerName = in.read_string ();
         String $result = null;
         $result = this.transferRecord (id, recordId, remoteCenterServerName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ca.concordia.dsd.arch/corba/killPrimaryServer
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.killPrimaryServer (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ca.concordia.dsd.arch/corba:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public corba _this() 
  {
    return corbaHelper.narrow(
    super._this_object());
  }

  public corba _this(org.omg.CORBA.ORB orb) 
  {
    return corbaHelper.narrow(
    super._this_object(orb));
  }


} // class corbaPOA
