package ca.concordia.dsd.arch;

/**
* ca.concordia.dsd.ca.concordia.dsd.arch/corbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.ca.concordia.dsd.idl
* Thursday, 5 August, 2021 2:30:22 PM EDT
*/

public final class corbaHolder implements org.omg.CORBA.portable.Streamable
{
  public  ca.concordia.dsd.arch.corba value = null;

  public corbaHolder ()
  {
  }

  public corbaHolder ( ca.concordia.dsd.arch.corba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value =  ca.concordia.dsd.arch.corbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
     ca.concordia.dsd.arch.corbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return  ca.concordia.dsd.arch.corbaHelper.type ();
  }

}
