package ca.concordia.dsd.arch;


/**
 * ca.concordia.dsd.ca.concordia.dsd.arch/corbaHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from corba.ca.concordia.dsd.idl
 * Thursday, 5 August, 2021 2:30:22 PM EDT
 */

abstract public class corbaHelper {
    private static final String _id = "IDL:ca.concordia.dsd.ca.concordia.dsd.arch/corba:1.0";
    private static org.omg.CORBA.TypeCode __typeCode = null;

    public static void insert(org.omg.CORBA.Any a, ca.concordia.dsd.arch.corba that) {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static ca.concordia.dsd.arch.corba extract(org.omg.CORBA.Any a) {
        return read(a.create_input_stream());
    }

    synchronized public static org.omg.CORBA.TypeCode type() {
        if (__typeCode == null) {
            __typeCode = org.omg.CORBA.ORB.init().create_interface_tc(ca.concordia.dsd.arch.corbaHelper.id(), "corba");
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static ca.concordia.dsd.arch.corba read(org.omg.CORBA.portable.InputStream istream) {
        return narrow(istream.read_Object(_corbaStub.class));
    }

    public static void write(org.omg.CORBA.portable.OutputStream ostream, ca.concordia.dsd.arch.corba value) {
        ostream.write_Object(value);
    }

    public static ca.concordia.dsd.arch.corba narrow(org.omg.CORBA.Object obj) {
        if (obj == null)
            return null;
        else if (obj instanceof ca.concordia.dsd.arch.corba)
            return (ca.concordia.dsd.arch.corba) obj;
        else if (!obj._is_a(id()))
            throw new org.omg.CORBA.BAD_PARAM();
        else {
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            ca.concordia.dsd.arch._corbaStub stub = new ca.concordia.dsd.arch._corbaStub();
            stub._set_delegate(delegate);
            return stub;
        }
    }

    public static ca.concordia.dsd.arch.corba unchecked_narrow(org.omg.CORBA.Object obj) {
        if (obj == null)
            return null;
        else if (obj instanceof ca.concordia.dsd.arch.corba)
            return (ca.concordia.dsd.arch.corba) obj;
        else {
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            ca.concordia.dsd.arch._corbaStub stub = new ca.concordia.dsd.arch._corbaStub();
            stub._set_delegate(delegate);
            return stub;
        }
    }

}
