package arch;

/**
* arch/corbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, 1 July, 2021 9:24:23 PM EDT
*/

public final class corbaHolder implements org.omg.CORBA.portable.Streamable
{
  public arch.corba value = null;

  public corbaHolder ()
  {
  }

  public corbaHolder (arch.corba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = arch.corbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    arch.corbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return arch.corbaHelper.type ();
  }

}
