package ca.concordia.dsd.arch;


/**
* arch/corbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, 1 July, 2021 9:24:23 PM EDT
*/

public interface corbaOperations 
{
  boolean createTRecord (String id, String fName, String lName, String address, String phone, String specialization, String location);
  boolean createSRecord (String id, String fName, String lName, String courses, boolean status, String statusDate);
  boolean getRecordCounts ();
  boolean editRecord (String id, String recordID, String fieldName, String newValue);
  boolean transferRecord (String id, String recordId, String remoteCenterServerName);
} // interface corbaOperations
