package ca.concordia.dsd.arch;


/**
* arch/corba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Friday, 2 July, 2021 10:52:21 PM EDT
*/

public interface corba extends corbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface corba
