package ca.concordia.dsd.arch;


/**
* arch/corba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Thursday, 1 July, 2021 9:24:23 PM EDT
*/

public interface corba extends corbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface corba
