package ca.concordia.dsd.arch;

/**
* arch/corbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Friday, 2 July, 2021 10:52:21 PM EDT
*/

public final class corbaHolder implements org.omg.CORBA.portable.Streamable
{
  public corba value = null;

  public corbaHolder ()
  {
  }

  public corbaHolder (corba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaHelper.type ();
  }

}
